import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-medicaid-duplicate-coverage-payment-recovery",
  "engine": "recovery",
  "title": "Medicaid Duplicate Coverage Payment Recovery",
  "shortTitle": "Medicaid Duplicate Coverage Payment Recovery",
  "tagline": "Find and recover capitation and claim payments made during overlapping or ineligible coverage periods.",
  "industry": "Medicaid Program Integrity",
  "buyer": "State Medicaid agencies and managed-care plans",
  "uiPort": 4641,
  "apiPort": 5641,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Medicaid Duplicate Coverage Payment Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices in one accountable workflow. Find and recover capitation and claim payments made during overlapping or ineligible coverage periods.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Medicaid Duplicate Coverage Payment Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("member-identity-resolution","MDC01","Member identity resolution","Execute member identity resolution using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed member identity resolution decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Member identity resolution Reference","text","MDC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("eligibility-span-ingestion","MDC02","Eligibility span ingestion","Execute eligibility span ingestion using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed eligibility span ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Eligibility span ingestion Reference","text","MDC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("interstate-coverage-matching","MDC03","Interstate coverage matching","Execute interstate coverage matching using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed interstate coverage matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Interstate coverage matching Reference","text","MDC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("medicare-overlap-detection","MDC04","Medicare overlap detection","Execute medicare overlap detection using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed medicare overlap detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Medicare overlap detection Reference","text","MDC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("marketplace-overlap-detection","MDC05","Marketplace overlap detection","Execute marketplace overlap detection using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed marketplace overlap detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Marketplace overlap detection Reference","text","MDC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("managed-care-enrollment-reconciliation","MDC06","Managed-care enrollment reconciliation","Execute managed-care enrollment reconciliation using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed managed-care enrollment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Managed-care enrollment reconciliation Reference","text","MDC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("capitation-overpayment-calculation","MDC07","Capitation overpayment calculation","Execute capitation overpayment calculation using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed capitation overpayment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Capitation overpayment calculation Reference","text","MDC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("fee-for-service-claim-review","MDC08","Fee-for-service claim review","Execute fee-for-service claim review using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed fee-for-service claim review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Fee-for-service claim review Reference","text","MDC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("retro-termination-validation","MDC09","Retro termination validation","Execute retro termination validation using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed retro termination validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Retro termination validation Reference","text","MDC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("provider-notification-workflow","MDC10","Provider notification workflow","Execute provider notification workflow using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed provider notification workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Provider notification workflow Reference","text","MDC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("member-due-process-evidence","MDC11","Member due-process evidence","Execute member due-process evidence using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed member due-process evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Member due-process evidence Reference","text","MDC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("plan-recovery-demand","MDC12","Plan recovery demand","Execute plan recovery demand using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed plan recovery demand decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Plan recovery demand Reference","text","MDC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("cash-recovery-tracking","MDC13","Cash recovery tracking","Execute cash recovery tracking using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed cash recovery tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Cash recovery tracking Reference","text","MDC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("eligibility-control-remediation","MDC14","Eligibility control remediation","Execute eligibility control remediation using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed eligibility control remediation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Eligibility control remediation Reference","text","MDC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]}),
feature("program-integrity-analytics","MDC15","Program integrity analytics","Execute program integrity analytics using eligibility spans, interstate matches, managed-care enrollments, claims, capitation payments, terminations, recoveries, and notices.","Produce a governed program integrity analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Coverage Episode","text","Member / Coverage Episode · Standard Case"],["caseReference","Program integrity analytics Reference","text","MDC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",480000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",580800],["domainDriver","Coverage Exception","select","Interstate duplicate",["Interstate duplicate","Medicare overlap","Marketplace overlap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member identity resolution case","Eligibility span ingestion case","Interstate coverage matching case","Medicare overlap detection case","Marketplace overlap detection case"]})
]);
